- name: IIS Update
  hosts: all
  gather_facts: no
  vars:
    ansible_test_staging_path: "{{ staging_path }}\\ansible-test-site-{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"

  tasks:
  - name: install-iis
    win_feature:
      name: "Web-Server"
      state: present
      restart: no
      include_sub_features: yes
      include_management_tools: no
  - name: create staging path
    win_file: path={{ staging_path }} state=directory

  - name: create new website's directory
    win_file: path={{ site_path }} state=directory
  - name: create new website
    win_iis_website:
      name: "{{ website_name }}"
      state: started
      port: {{ website_port }}
      physical_path: "{{ site_path }}"
  - name: Open site's port on firewall
    win_firewall_rule:
      name: {{ firewall_rule_name }}
      enable: yes
      state: present
      localport: {{ website_port }}
      action: Allow
      direction: In
      protocol: Tcp
      force: true
    tags: firewall

  - name: unzip code to site path
    win_unzip:
      src: "{{ ansible_test_staging_path }}\\{{ src_zip_file }}"
      dest: "{{ site_path }}"
      creates: "{{ site_path }}\\index.html"
    tags: unzip
