- name: IIS Update
  hosts: all
  gather_facts: no
  
  tasks:
  - name: create new website's directory
    win_file: path={{ site_path }} state=directory

  - name: stop website
    win_iis_website:
      application_pool: "{{ application_pool }}"
      name: "{{ website_name }}"
      port: "{{ website_port }}"
      ssl: "{{ website_ssl }}"
      ip: "{{ website_ip }}"
      physical_path: "{{ site_path }}"
      state: stopped

  - name: unzip code to site path
    win_unzip:
      src: "{{ src_zip_file }}"
      dest: "{{ site_path }}"
    tags: unzip

  - name: start website
    win_iis_website:
      application_pool: "{{ application_pool }}"
      name: "{{ website_name }}"
      port: "{{ website_port }}"
      ssl: "{{ website_ssl }}"
      ip: "{{ website_ip }}"
      state: started
