- name: NS Update
  hosts: all
  gather_facts: no

  tasks:
    - pip: 
        name: dnspython

    - name: Add or modify www.linuxconfig.org A to 192.168.1.1"
      nsupdate:
       key_name: "my-key-name"
       key_secret: "I1D5ZJq+2EkGP0p/69PDaVZJ8BrGNDA40Y6Dc2dBD9zBY674JFdeTXI+AaEgxhH/QbpiGi3rYF1B3FV4dEZFNQ=="
       server: "192.168.3.96"
       zone: "linuxconfig.org"
       record: "www"
       value: "192.168.1.1"
