- name: NS Update
  hosts: all
  gather_facts: no
  key_file: /keys/id_rsa
  
  tasks:
    - pip: 
        name: dnspython

    - name: Add or modify {{ record }}.{{ zone }} A to {{ new_ip }}"
      nsupdate:
       key_name: "{{ tsiguser }}"
       key_secret: "{{ tsigpass }}"
       server: "{{ server_ip }}"
       zone: "{{ zone }}"
       record: "{{ record }}"
       value: "{{ new_ip }}"
