- name: NS Update
  hosts: all
  gather_facts: no

  tasks:
    - pip: 
        name: dnspython

    - name: Add or modify {{ record }}.{{ zone }} A to {{ new_ip }}"
      nsupdate:
       key_name: "{{ tsiguser }}"
       key_secret: "{{ tsigpass }}"
       server: "{{ server }}"
       zone: "{{ zone }}"
       record: "{{ record }}"
       value: "{{ new_ip }}"
